export const doctor_categories = [
  { label: "Dr. Batra", value: "batra" },
  { label: "Dr. Mishra", value: "mishra" },
  { label: "Dr. Mehta", value: "mehta" },
  { label: "Dr. Bhatt", value: "bhatt" },
  { label: "Dr. Sanepara", value: "sanepara" },
  { label: "Dr. Varasada", value: "varasada" },
  { label: "Dr. Shukla", value: "shukla" },
  { label: "Dr. Gadhvi", value: "gadhvi" },
  // { label: "Endocrinologist", value: "endocrinologist" },
  // { label: "Urologist", value: "urologist" },
  // { label: "Oncologist", value: "oncologist" },
  // { label: "ENT Specialist (Otolaryngologist)", value: "ent_specialist" },
  // { label: "General Surgeon", value: "general_surgeon" },
  // { label: "Family Medicine Physician", value: "family_medicine_physician" },
  // {
  //   label: "Internal Medicine Physician",
  //   value: "internal_medicine_physician",
  // },
  // { label: "Radiologist", value: "radiologist" },
  // { label: "Anesthesiologist", value: "anesthesiologist" },
  // {
  //   label: "Emergency Medicine Physician",
  //   value: "emergency_medicine_physician",
  // },
  // { label: "Plastic Surgeon", value: "plastic_surgeon" },
  // { label: "Allergist/Immunologist", value: "allergist_immunologist" },
  // { label: "Rheumatologist", value: "rheumatologist" },
  // { label: "Nephrologist", value: "nephrologist" },
  // { label: "Pulmonologist", value: "pulmonologist" },
  // { label: "Geriatrician", value: "geriatrician" },
  // {
  //   label: "Infectious Disease Specialist",
  //   value: "infectious_disease_specialist",
  // },
  // { label: "Hematologist", value: "hematologist" },
  // { label: "Sports Medicine Physician", value: "sports_medicine_physician" },
  // { label: "Rehabilitation Specialist", value: "rehabilitation_specialist" },
  // { label: "Pain Management Specialist", value: "pain_management_specialist" },
  // { label: "Pathologist", value: "pathologist" },
  // { label: "Hospitalist", value: "hospitalist" },
  // { label: "Sleep Medicine Specialist", value: "sleep_medicine_specialist" },
  // { label: "Intensivist", value: "intensivist" },
  // { label: "Forensic Pathologist", value: "forensic_pathologist" },
  // { label: "Clinical Geneticist", value: "clinical_geneticist" },
  // { label: "Podiatrist", value: "podiatrist" },
  // { label: "Dietitian/Nutritionist", value: "dietitian_nutritionist" },
  // { label: "Chiropractor", value: "chiropractor" },
  // {
  //   label: "Physiatrist (Physical Medicine and Rehabilitation Physician)",
  //   value: "physiatrist",
  // },
  // { label: "Occupational Therapist", value: "occupational_therapist" },
  // { label: "Speech Therapist", value: "speech_therapist" },
  // { label: "Optometrist", value: "optometrist" },
  // { label: "Audiologist", value: "audiologist" },
  // { label: "Naturopathic Doctor", value: "naturopathic_doctor" },
  // { label: "Acupuncturist", value: "acupuncturist" },
  // { label: "Homeopath", value: "homeopath" },
  // { label: "Ayurvedic Doctor", value: "ayurvedic_doctor" },
  // {
  //   label: "Traditional Chinese Medicine Practitioner",
  //   value: "tcm_practitioner",
  // },
  // { label: "Herbalist", value: "herbalist" },
  // { label: "Nurse Practitioner", value: "nurse_practitioner" },
  // { label: "Physician Assistant", value: "physician_assistant" },
];
